name: Build & Push to Docker Hub

on:
  push:
    branches: ["dev"]
    tags: ["v*"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            funmicra/docker-update:latest
            funmicra/docker-update:${{ github.sha }}
            funmicra/docker-update:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # optional: serialize uploads to reduce 400 errors
          max-concurrent-uploads: 1

      - name: Pull new image
        run: docker pull funmicra/docker-update:latest

      - name: Stop old container
        run: |
          docker stop docker-update || true
          docker rm docker-update || true

      - name: Run updated container
        run: |
          docker run -d \
            --name docker-update \
            --restart unless-stopped \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v logs:/app/logs \
            --env-file /opt/auto-update/.env \
            funmicra/docker-update:latest
